# Generated by Django 5.0.1 on 2024-05-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Expired', 'Expired'), ('Declined', 'Declined'), ('Removed', 'Removed'), ('Approved', 'Approved')], default='Pending', max_length=10),
        ),
    ]
