# Generated by Django 5.0.4 on 2024-05-16 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '__first__'),
        ('employer', '__first__'),
        ('jobseeker', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('haveseen', models.BooleanField(default=False)),
                ('sender', models.TextField()),
                ('filepath', models.FileField(blank=True, null=True, upload_to='message/file')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employer')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.jobseeker')),
            ],
        ),
    ]
