# Generated by Django 5.0.4 on 2024-05-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='filepath',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
