# Generated by Django 5.0.4 on 2024-05-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_message_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='filepath',
            field=models.FileField(blank=True, null=True, upload_to='message/file'),
        ),
    ]
